---
- name: get build image, git clone repo, get deps, build artifact
  hosts: web
  become: yes

  tasks:

  - name: Ensure git,maven,default jdk is present
    apt: pkg={{ item }}
    with_items: 
      - git
      - maven
      - default-jdk
    update_cache: yes
    state: present

  - name: Ensure git cloned sample webapp repo
     git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/buildhere/
      clone: yes

  - name: Ensure artifact is built from source
    command: mvn -f /home/buildhere/boxfuse/pom.xml clean package

- name: Run built artefact
  hosts: web
  become: yes
  tasks:
  - name: copy built artifact to remote
    copy: src=/tmp/artifact/hello-world-1.0-SNAPSHOT.jar dest=/runme/hello-world-1.0-SNAPSHOT.jar
  
  - name: ensure jar file is present
    

  - name: run built artifact
    shell: java -jar /runme/hello-world-1.0-SNAPSHOT.jar