---
- name: get build image, git clone repo, get deps, build artifact
  hosts: web
  become: yes

  tasks:

  - name: Ensure git,maven,default jdk is present
    apt: pkg={{ item }}
    with_items: 
      - git
      - maven
      - default-jdk
    update_cache: yes
    state: present

  - name: Ensure git cloned sample webapp repo
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/buildhere/
      clone: yes

  - name: Ensure artifact is built from source
    command: mvn -f /home/buildhere/boxfuse/pom.xml clean package

- name: Run built artefact in production env
  hosts: web
  become: yes

  tasks:
  
  - name: Ensure JRE and tomcat9 is present
    apt: pkg={{ item }}
    with_items: 
      - tomcat9
      - default-jre
    update_cache: yes
    state: present
  
  - name: Ensure webserver tomcat is runnung
    service:
      name: tomcat9
      state: started

  - name: Ensure test webapp is synchorized with production node
    synchorize:
      src: /home/buildhere/boxfuse/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps
      delegate_to: web
   
